<?php
/**
 * Copyright © Encora, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */

$columnsLimit = $block->getColumnsLimit() ?: 0;
$_menuHtml = $block->getHtml('level-top', 'submenu', $columnsLimit)
?>
<div class="left-category-container">
    <div class="heading"><h2><?php echo __('Category'); ?></h2></div>
    <nav class="navigation" data-action="navigation">
        <ul data-mage-init='{"menu":{"responsive":true, "mediaBreakpoint": "(max-width: 1400px)", "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
            <?= /* @noEscape */ $_menuHtml?>
            <?= $block->getChildHtml() ?>
        </ul>
    </nav>
</div>

